export enum ApiErrorCode {
  INVALID_TOKEN = "INVALID_TOKEN_ERROR",
  CONFLICT        = "CONFLICT_ERROR",
  AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  NOT_FOUND        = "NOT_FOUND",
}