//Roles
const ADMIN_ROLE_ID = 1;
const EMPLOYEE_ROLE_ID = 2;

//Rutas
const HOME_PATH = "/";
const ADMIN_HOME_PATH = "/inicio-admin";
const EMPLOYEE_HOME_PATH = "/inicio-employee";
const CREATE_ADMIN_PATH = "/create-admin";
const INVENTORY_PATH = "/inventario";
const SALES_PATH = "/ventas";
const REPORTS_PATH = "/reportes";
const EMPLOYEES_PATH = "/empleados";

//Roles por ruta
const INVENTORY_ALLOWED_ROLES = [ADMIN_ROLE_ID, EMPLOYEE_ROLE_ID];
const HOME_ALLOWED_ROLES = [ADMIN_ROLE_ID, EMPLOYEE_ROLE_ID];
const ADMIN_HOME_ALLOWED_ROLES = [ADMIN_ROLE_ID];
const EMPLOYEE_HOME_ALLOWED_ROLES = [EMPLOYEE_ROLE_ID];
const SALES_ALLOWED_ROLES = [EMPLOYEE_ROLE_ID, ADMIN_ROLE_ID];
const REPORTS_ALLOWED_ROLES = [ADMIN_ROLE_ID];
const EMPLOYEES_ALLOWED_ROLES = [ADMIN_ROLE_ID];

//Rutas backend
const BACKEND_LOGIN_URL = "/api/auth/login";
const BACKEND_REGISTER_ADMIN_URL = "/api/users/register-initial-admin";
const BACKEND_CHECK_ADMIN_URL = "/api/users/admin-exists";

export const constants = {
  HOME_PATH,
  ADMIN_HOME_PATH,
  EMPLOYEE_HOME_PATH,
  CREATE_ADMIN_PATH,
  INVENTORY_PATH,
  SALES_PATH,
  REPORTS_PATH,
  EMPLOYEES_PATH,
  ADMIN_ROLE_ID,
  EMPLOYEE_ROLE_ID,
  INVENTORY_ALLOWED_ROLES,
  HOME_ALLOWED_ROLES,
  SALES_ALLOWED_ROLES,
  REPORTS_ALLOWED_ROLES,
  EMPLOYEES_ALLOWED_ROLES,
  ADMIN_HOME_ALLOWED_ROLES,
  EMPLOYEE_HOME_ALLOWED_ROLES,
  BACKEND_LOGIN_URL,
  BACKEND_REGISTER_ADMIN_URL,
  BACKEND_CHECK_ADMIN_URL,
};